
version: 2

models:
  - name: BRONZE_FLIGHTS
    description: "A starter dbt model"
    columns:
      - name: TRANSACTIONID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

